######################################################################
# Automatically generated by qmake (3.1) Sat Sep 27 16:44:15 2025
######################################################################

TEMPLATE = app
TARGET = step01
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += cmake-build-debug/step01_autogen/KEXXALT6CP/moc_QtAwesome.cpp \
           C:/Dev/Code/git-projects/ChocolafStyle/chocolaf/common_files/QtAwesome/QtAwesome.h \
           C:/Dev/Code/git-projects/ChocolafStyle/chocolaf/common_files/QtAwesome/QtAwesomeAnim.h \
           C:/Dev/Code/git-projects/ChocolafStyle/chocolaf/common_files/QtAwesome/QtAwesomeEnumGenerated.h \
           cmake-build-debug/step01_autogen/KEXXALT6CP/moc_QtAwesomeAnim.cpp
SOURCES += step01.cc \
           cmake-build-debug/step01_autogen/mocs_compilation.cpp \
           cmake-build-debug/step01_autogen/5IGWCDV6FB/qrc_chocolaf.cpp \
           cmake-build-debug/step01_autogen/KEXXALT6CP/qrc_QtAwesomeFree.cpp \
           cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           Debug/build/debug/.qrc/qrc_chocolaf.cpp \
           Debug/build/debug/.qrc/qrc_QtAwesomeFree.cpp \
           C:/Dev/Code/git-projects/ChocolafStyle/chocolaf/common_files/QtAwesome/QtAwesome.cpp \
           C:/Dev/Code/git-projects/ChocolafStyle/chocolaf/common_files/QtAwesome/QtAwesomeAnim.cpp
RESOURCES += Debug/build/debug/.qrc Debug/build/release/.qrc
