""" this code has been generated by Google Gemini LLM """
import yfinance as yf
import pandas as pd
import mplfinance as mpf
import matplotlib.pyplot as plt

# Download stock prices from Yahoo Finance
ticker = "PIDILITIND.NS"
data = yf.download(ticker, start="2023-11-01", end="2024-02-29")

# Calculate EMA for periods 12, 23 and 200
data["EMA_12"] = data["Close"].ewm(span=12, adjust=False).mean()
data["EMA_23"] = data["Close"].ewm(span=23, adjust=False).mean()
data["EMA_200"] = data["Close"].ewm(span=200, adjust=False).mean()

# Calculate Bollinger Bands 20 periods with 2 std deviations
data["BB_20_upper"] = (
    data["Close"].rolling(window=20).mean() + 2 * data["Close"].rolling(window=20).std()
)
data["BB_20_lower"] = (
    data["Close"].rolling(window=20).mean() - 2 * data["Close"].rolling(window=20).std()
)

# Calculate EMA for periods 13, 26, 50 and 200
data["EMA_13"] = data["Close"].ewm(span=13, adjust=False).mean()
data["EMA_26"] = data["Close"].ewm(span=26, adjust=False).mean()
data["EMA_50"] = data["Close"].ewm(span=50, adjust=False).mean()
data["EMA_200"] = data["Close"].ewm(span=200, adjust=False).mean()

# Plot OHLC candlesticks, with volume, EMAs calculated and bollinger bands
mpf.plot(
    data,
    type="candle",
    volume=True,
    style="yahoo",
    title=f"{ticker}",
    mav=(12, 23, 200),
    # bollinger=(20, 2),
    tight_layout=True,
)
# plt.legend(loc="best")
plt.show()
