######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 25 00:57:07 2015
######################################################################

TEMPLATE = app
TARGET = factorial

# include (/home/mjbhobe/code/git-projects/ChocolafStyle/chocolaf/common_files/common_console.pro)
include ($$system(CHOCOLAF_COMMONFILES_HOME)/common_console.pro)

# Input
SOURCES += factorial.cc
